spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:petclinic.db?date_class=TEXT&date_string_format=yyyy-MM-dd
spring.datasource.username=
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/sqlite/schema.sql
spring.sql.init.data-locations=classpath:db/sqlite/data.sql
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
